### ISSUE TITLE
Justera Ai

### ISSUE THREAD

**Issue by ztime** [ztime/imperiled#2]
Justera våran awsome Ai så att spelet inte är omöjligt ;)

**Comment by johnwikman** [comment]
Lade till en aggrorange på biet samt att den får en annan hastighet när den väl attackerar. Kolla i branchen johnsbranch.

**Comment by ztime** [comment]
Grymt! ska vi säga att ai:n är klar för demon där ?

**Comment by johnwikman** [comment]
Ai är demo-redo.
Det som har lagts till är en PathFinder klass, en AI klass, en Behaviour enumerator och en aggro range för actors.
